meta:
  author: CABeale
  boardName: BadWings
units:
  kx: cx
  ky: cy

  px: kx + 2
  py: ky + 2

  pushX: (kx/2)
  pushY: (ky/2)

  padX: pushX + 2
  padY: pushY + 2

  # nice!nano dimensions
  controllerW: 18.5
  controllerH: 33.5
  # nice!view dimensions
  nice_viewW: 14
  nice_viewH: 36
  # EC11 rotary dimensions
  rotaryW: 11.7
  rotaryH: 12

# TODO Change all key pins to use LF rather than HF to allow for room for LEDs
points:
  zones:
    fingers:
      # Fix placement on KiCAD Sheet
      anchor:
        shift: [100, -200]
      rotate: 23
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key.column_net: P020
        ring:
          key.stagger: 0.6kx
          key.splay: -12
          key.origin: [0, -17]
          key.column_net: P022
        middle:
          key.stagger: 0.35kx
          key.splay: -7
          key.origin: [-10, -17]
          key.column_net: P024
        index:
          key.stagger: -0.4kx
          key.splay: -4
          key.origin: [-10, -16]
          key.column_net: P100
        inner:
          # key.stagger: -0.1kx
          key.column_net: P011
      rows:
        bottom:
          row_net: P002
        home:
          row_net: P029
        top:
          row_net: P031
    thumbfan:
      anchor:
        ref: fingers_index_bottom
        shift: [0.55kx, -1.5ky]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        left:
          rows.bottom.width: 1.25kx
          rows.top.skip: true
          key.splay: -15
          key.column_net: P024
        middle:
          rows.top.width: 1.25ky
          rows.top.rotate: 90
          key.stagger: -0.45ky
          key.padding: 1.2ky
          key.splay: -2
          key.spread: 22
          key.column_net: P100
        right:
          rows.top.width: 1.25ky
          rows.top.rotate: 90
          key.stagger: -0.2ky
          key.padding: 1.2ky
          key.splay: -2
          key.spread: 19
          key.column_net: P011
      rows:
        bottom:
          row_net: P113
        top:
          row_net: P115
    rotary:
      # This needs to be an EC11 rotary encoder
      anchor:
        ref: fingers_inner_bottom
        shift: [2kx +4, -4]
      columns:
        rotaryCol:
          key:
            key.column_net: P017
      rows:
        rotaryRow:
          row_net: P002
    # NICE!NANO - used for layout testing
    controller:
      anchor:
        ref: fingers_inner_top
        shift: [20, -11]
      columns:
        controllerCol:
          rows.controllerRow.height: controllerH
          rows.controllerRow.width: controllerW
      rows:
        controllerRow:

    # NICE!VIEW - used for layout testing
    # nice_view:
    #   anchor:
    #     ref: fingers_inner_top
    #     shift: [20, -13]
    #   columns:
    #     nice_viewCol:
    #       rows.nice_viewRow.height: nice_viewH
    #       rows.nice_viewRow.width: nice_viewW
    #   rows:
    #     nice_viewRow:

    # BATTERY - used for layout testing
    # battery:
    #   anchor:
    #     ref: fingers_inner_top
    #     shift: [-kx, -ky]
    #     rotate: 90
    #   #PLACEMENT: Battery goes underneath the board
    #   columns:
    #     batteryC:
    #       rows.batteryR.height: batteryH
    #       rows.batteryR.width: batteryW
    #   rows:
    #     batteryR:
  mirror: &mirror
    ref: fingers_inner_top
    distance: 6kx

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx - 0.5, ky - 0.5]
  board_left:
    # Here to help trace the outline of the actual keys
    # without this the polygon would have been a total shot in the dark
    # - where: true
    #   operation: stack
    #   what: rectangle
    #   size: [kx, ky]

    - what: polygon

      fillet: 2
      points:
        #FINGERS - top
        #pinky
        - ref: fingers_pinky_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: fingers_pinky_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #ring
        - ref: fingers_ring_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: fingers_ring_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #middle
        - ref: fingers_middle_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: fingers_middle_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #index
        - ref: fingers_index_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: fingers_index_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #inner
        - ref: fingers_inner_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: fingers_inner_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #CONTROLLER
        - ref: fingers_inner_top
          # shift: [padX + controllerW, padY]
          shift: [0.7px + controllerW, 0.5py]
        #ROTARY
        - ref: rotary_rotaryCol_rotaryRow
          # shift: [-padX, padY]
          shift: [-0.35px, 0.5py]
        - ref: rotary_rotaryCol_rotaryRow
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        - ref: rotary_rotaryCol_rotaryRow
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
        #THUMBS
        #top
        # - ref: thumbfan_right_top
        #   shift: [padX, padY]
        - ref: thumbfan_right_top
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
        #bottom
        - ref: thumbfan_right_bottom
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
        - ref: thumbfan_right_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        - ref: thumbfan_middle_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        - ref: thumbfan_left_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        # FINGERS - bottom
        - ref: fingers_index_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        - ref: fingers_ring_bottom
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
        - ref: fingers_pinky_bottom
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
        - ref: fingers_pinky_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        #Connect back to top
        - ref: fingers_pinky_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
  combo_left:
    - name: board_left
    - operation: subtract
      name: keys
  board_right:
    # Here to help trace the outline of the actual keys
    # without this the polygon would have been a total shot in the dark
    # - where: true
    #   operation: stack
    #   what: rectangle
    #   size: [kx, ky]

    - what: polygon
      operation: stack
      fillet: 2
      points:
        #FINGERS - top
        #pinky
        - ref: mirror_fingers_pinky_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: mirror_fingers_pinky_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #ring
        - ref: mirror_fingers_ring_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: mirror_fingers_ring_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #middle
        - ref: mirror_fingers_middle_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: mirror_fingers_middle_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #index
        - ref: mirror_fingers_index_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: mirror_fingers_index_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #inner
        - ref: mirror_fingers_inner_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
        - ref: mirror_fingers_inner_top
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        #CONTROLLER
        - ref: mirror_fingers_inner_top
          # shift: [padX + controllerW, padY]
          shift: [0.7px + controllerW, 0.5py]
        #ROTARY
        - ref: mirror_rotary_rotaryCol_rotaryRow
          # shift: [-padX, padY]
          shift: [-0.35px, 0.5py]
        - ref: mirror_rotary_rotaryCol_rotaryRow
          # shift: [padX, padY]
          shift: [0.5px, 0.5py]
        - ref: mirror_rotary_rotaryCol_rotaryRow
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
        #THUMBS
        #top
        # - ref: thumbfan_right_top
        #   shift: [padX, padY]
        - ref: mirror_thumbfan_right_top
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
          #bottom
        - ref: mirror_thumbfan_right_bottom
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
        - ref: mirror_thumbfan_right_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        - ref: mirror_thumbfan_middle_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        - ref: mirror_thumbfan_left_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        # FINGERS - bottom
        - ref: mirror_fingers_index_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        - ref: mirror_fingers_ring_bottom
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
        - ref: mirror_fingers_pinky_bottom
          # shift: [padX, -padY]
          shift: [0.5px, -0.5py]
        - ref: mirror_fingers_pinky_bottom
          # shift: [-padX, -padY]
          shift: [-0.5px, -0.5py]
        #Connect back to first point
        - ref: mirror_fingers_pinky_top
          # shift: [-padX, padY]
          shift: [-0.5px, 0.5py]
  combo_right:
    - name: board_right
    - operation: subtract
      name: keys

pcbs:
  badWingsLeft:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: /^fingers_.*|^thumbfan_.*/
        params:
          keycaps: true
          reverse: false # Top side only
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          # Rotate the key switches upside-down
          rotate: 180

      # DIODE
      diode_main:
        # what: diode
        what: diode_tht_sod123
        where: /^fingers_.*|^thumbfan_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.3, 0]
          # rotate: 90
          rotate: -90

      # CONTROLLER
      nice_nano:
        what: nice_nano
        params:
          orientation: down
        where:
          ref: fingers_inner_top
          shift: [21, -9.5]
          rotate: -90

      nice_view:
        what: nice_view
        params:
          SDA: P017
          SCL: P020
          CS: P006
        where:
          ref: fingers_inner_top
          shift: [21, -30]
          rotate: 90

      # LEDs
      per_key_leds:
        what: led_sk6812mini-e
        where: /^fingers_.*|^thumbfan_.*|^controller_(?!(?:controllerCol_controllerRow))|^rotary_(?!(?:rotaryCol_rotaryRow))/
        params:
          P2: "{{key.led_next}}" #DOUT
          P4: "{{key.led_prev}}" #DIN
        adjust:
          shift: [0, 5]

      #TODO - Find alternative location because of encoder placement (this will give room for the reset/pwr btns)
      # BATTERY JACK
      jstph:
        what: jstph
        where:
          ref: fingers_inner_bottom
          shift: [2.2kx, 2]
          rotate: -90
        params:
          side: B
          pos: pos
          neg: GND

      #TODO - Wrong placement because of 1.25u keycap!
      # ENCODER
      encoder:
        # what: rotary_encoder_ec11_ec12
        what: rotary
        where:
          ref: thumbfan_right_top
          rotate: 90
          shift: [1px - 3.5, 0.15py]
        params:
          from: P009 # Push button (S1 - RevXL ref)
          to: P010 # Push button (S2 RevXL ref)
          A: P111 # Rotary
          B: GND
          C: P113 # Rotary

      # ENCODER - Diode
      encoder_diode:
        what: diode
        where:
          ref: thumbfan_right_top
          shift: [1px - 3, 0.65py]
        params:
          from: endiode
          to: row4

      # RESET SWITCH
      # horizontal_reset:
      #   what: EVQPUC
      #   params:
      #     side: B
      #     from: GND
      #     to: RST
      #   where:
      #     ref: fingers_inner_top
      #     shift: [9.0, 2.8]
      #     rotate: -90

      # MOUNTING HOLES
      hole_bottom_right:
        what: mountinghole
        where:
          ref.aggregate.parts: [thumbfan_middle_top, thumbfan_right_bottom]

      hole_bottom_left:
        what: mountinghole
        where:
          ref.aggregate.parts: [fingers_pinky_bottom, fingers_ring_bottom]
          shift: [0.25kx, -0.45ky]

      hole_top_left:
        what: mountinghole
        where:
          ref.aggregate.parts: [fingers_pinky_top, fingers_ring_top]

      hole_top_right:
        what: mountinghole
        where:
          ref.aggregate.parts: [fingers_index_top, fingers_inner_home]

      hole_far_right:
        what: mountinghole
        where:
          ref: fingers_inner_bottom
          shift: [2.6kx, 2]

      hole_center:
        what: mountinghole
        where:
          ref.aggregate.parts: [fingers_index_home, fingers_index_bottom]
          shift: [-0.5kx, 0]

      # Write "Bad Wings" on the PCB
      # front_text: &text
      #   what: text
      #   where: &textWhere
      #     ref: fingers_index_bottom
      #     shift: [-8.7, -5.5]
      #   params: &textParams
      #     text: BadWings
      #     justify: left
      #     style: italic
      #     h_size: 3.0
      #     v_size: 3.0
      #     thickness: 0.4

  # badWingsRight:
  #   outlines:
  #     main:
  #       outline: board_right
  #   footprints:
  #     choc_hotswap:
  #       what: choc
  #       where: /^mirror_fingers_.*/
  #       params:
  #         keycaps: true
  #         reverse: false
  #         hotswap: true
  #         from: "{{column_net}}"
  #         to: "{{colrow}}"
  #       adjust:
  #         # Rotate the key switches upside-down
  #         rotate: 180

  #     # DIODE - FINGERS
  #     diode_main:
  #       what: diode
  #       where: /^mirror_fingers_.*/
  #       params:
  #         from: "{{colrow}}"
  #         to: "{{row_net}}"
  #       adjust:
  #         shift: [-7.8, -3.5]
  #         rotate: 90

  #     # DIODE - THUMBS
  #     diode_thumbs:
  #       what: diode
  #       where: /^mirror_thumbfan_.*/
  #       params:
  #         from: "{{colrow}}"
  #         to: "{{row_net}}"
  #       adjust:
  #         shift: [-7.8, -3.5]
  #         rotate: -90

  #     # CONTROLLER
  #     nice_nano:
  #       what: nice_nano
  #       params:
  #         orientation: down
  #       where:
  #         ref: mirror_fingers_inner_top
  #         shift: [-21, -9.5]
  #         rotate: -90

  #     # BATTERY JACK
  #     jstph:
  #       what: jstph
  #       where:
  #         ref: mirror_fingers_inner_home
  #         shift: [-7, 5.7]
  #         rotate: -90
  #       params:
  #         side: B
  #         pos: pos
  #         neg: GND

  #     # ENCODER
  #     encoder:
  #       what: rotary_encoder_ec11_ec12
  #       where:
  #         ref: mirror_rotary_rotaryCol_rotaryRow

  #     # ENDODER - Diode
  #     # encoder_diode:
  #     #   what: diode
  #     #   where:
  #     #     ref: mirror_rotary_rotaryCol_rotaryRow
  #     #   params:
  #     #     from: endiode
  #     #     to: row4

  #     # PLACEHOLDER STUFF FOR LATER
  #     # LEDS
  #     # sk6813:
  #     #   what: led_sk6812mini-e
  #     #   where: true
  #     #   params:
  #     #     # TODO: Change P to appropriate PIN on controller
  #     #     P2: "{{key.led_next}}" #DOUT
  #     #     P4: "{{key.led_prev}}" #DIN
  #     #   adjust:
  #     #     shift: [0, 5]
  #     #     rotate: 0
  #     # Encoder
  #     # TODO: Encoder may need its own pins on the MC
  #     # encoder:
  #     #   what: rotary_encoder_ec11_ec12
  #     #   params:
  #     #     S1: col5
  #     #     S2: endiode
  #     #     A: rotA
  #     #     B: GND
  #     #     c: rotB
  #     #   where:
  #     #     - ref: rotary_rotaryCol_rotaryRow
  #     # encoder_diode:
  #     #   # TODO: what is this diode?
  #     #   what: diode_tht_sod123
  #     #   where:
  #     #     - ref: rotary_rotaryCol_rotaryRow
  #     #       # TODO: Find the right place for this
  #     #       shift: [0, -5]
